version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - run: 
          name: figure out working dir
          command: |
            ls
      - run:
          name: Setting up environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip3 install -r Dependencies.txt
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python3 -m unittest

workflows:
  build-and-run:
    jobs:
      - build_and_test
